app = "gpu-stress-test"
primary_region = "ord"
host_dedication_id = "fly_gpus_stress_test"

[processes]
40gb = ""
80gb = ""

[[vm]]
size = "a100-80gb"
processes = ["80gb"]

[[vm]]
size = "a100-40gb"
processes = ["40gb"]
