app = "gpu-stress-test"
primary_region = "ord"
host_dedication_id = "fly_gpus_stress_test"

#[build]
#image = "dangra/gpu-burn"

[processes]
40gb = ""
80gb = ""
l40s = ""
a10  = ""

[[restart]]
policy = 'always'
processes = ['40gb', '80gb', 'l40s', 'a10']

[[vm]]
size = "a100-80gb"
cpus = 16
processes = ["80gb"]

[[vm]]
size = "a100-40gb"
cpus = 16
processes = ["40gb"]

[[vm]]
size = "l40s"
cpus = 16
processes = ["l40s"]

[[vm]]
size = "a10"
cpus = 16
processes = ["a10"]
